---
- hosts: all
  gather_facts: no
  become: yes
  vars_files:
    - vars.yml
  tasks:

  - name: One-time setup (add repository, install python-xml)
    shell: |
      zypper ar {{ clouddata.http_root }}/repos/SLES12-SP1-Pool/ sles12sp1 &&
      zypper ar {{ clouddata.http_root }}/repos/SLES12-SP1-Updates/ sles12sp1up &&
      zypper ar {{ clouddata.http_root }}/repos/SUSE-Cloud-6-Pool/ clud6 &&
      zypper -qn up &&
      zypper -qn in python-xml &&
      touch /root/one-time-setup-completed
    args:
      creates: /root/one-time-setup-completed

  - name: Install RabbitMQ-Server
    zypper:
      name: rabbitmq-server
      state: present

  - name: Amend hosts file
    template:
      dest: /etc/hosts
      src: hosts.j2

  - name: Stop Rabbit
    service:
      name: rabbitmq-server
      state: stopped

  - name: Set erlang cookie
    copy:
      dest: /var/lib/rabbitmq/.erlang.cookie
      mode: 0400
      owner: rabbitmq
      group: rabbitmq
      content: GMMJOOASEJDGSCNPYSQZ

  - name: Copy rabbitmq configuration file
    template:
      src: rabbitmq.config.j2
      dest: /etc/rabbitmq/rabbitmq.config
      mode: 0644
      owner: root
      group: root

  - name: Stop Rabbit
    service:
      name: rabbitmq-server
      state: started


